import ReadableText from './ReadableText.jsx';
import React from 'react';
const content={
ja:{title:'お手本まで、\nあなたに合わせる。',intro:'発音をチェックする。その先に、自分の声で練習するという選択。',columns:['学び方','AI発音アプリ','添削型シャドーイング','Lanclo'],rows:[['お手本','一部に本人声のプレビュー','本人声は未確認','あなたの声のAIお手本'],['フィードバック','AIが発音を評価','人が録音を添削','AIが発音を分析'],['次の練習','個別の学習プラン','教材選び・提案','結果から次の練習を構成'],['続けるきっかけ','ニュース対応は未確認','ニュース対応は未確認','興味のあるニュースも教材に']],note:'代表的なサービスの公式情報を比較（2026年10月）。△は提供範囲・プランによる違い、—は未確認で「非対応」ではありません。精度・学習効果の優劣を示すものではありません。'},
en:{title:'Even the model\nis made for you.',intro:'Beyond checking pronunciation: practice with a model in your own voice.',columns:['Learning approach','AI pronunciation apps','Human-reviewed shadowing','Lanclo'],rows:[['Model voice','Own-voice preview in some apps','Own voice not verified','Your own AI voice'],['Feedback','AI assessment','Human review','AI pronunciation analysis'],['Next practice','Personal learning plan','Material selection / advice','Practice assembled from results'],['Daily motivation','News not verified','News not verified','News that interests you']],note:'Representative official sources, October 2026. △ means scope varies; — means unverified, not unavailable. This does not rank accuracy or learning outcomes.'},
ko:{title:'발음 예시까지,\n나에게 맞게.',intro:'발음 확인에서 한 걸음 더. 내 목소리의 예시로 연습하세요.',columns:['학습 방식','AI 발음 앱','첨삭형 섀도잉','Lanclo'],rows:[['발음 예시','일부 본인 음성 미리 듣기','본인 음성 미확인','내 목소리의 AI 예시'],['피드백','AI 평가','사람의 녹음 첨삭','AI 발음 분석'],['다음 연습','개인 학습 계획','교재 선택·추천','결과 기반 연습 구성'],['꾸준함의 계기','뉴스 지원 미확인','뉴스 지원 미확인','관심 있는 뉴스도 교재로']],note:'대표 서비스의 공식 정보 기준(2026년 10월). △는 제공 범위 차이, —는 미확인이며 미지원이라는 뜻이 아닙니다. 정확도·학습 효과의 순위가 아닙니다.'}
};
const legends={ja:'○ 対応　△ サービス・プランによる　— 今回の調査では未確認',en:'○ Available　△ Varies by service / plan　— Not verified in this review',ko:'○ 지원　△ 서비스·요금제에 따라 다름　— 이번 조사에서 미확인'};
const features={ja:['自分の声のお手本','発音のフィードバック','結果に合わせた次の練習','興味のあるニュース教材'],en:['A model in your voice','Pronunciation feedback','Next practice based on results','News matched to your interests'],ko:['내 목소리의 발음 예시','발음 피드백','결과에 맞춘 다음 연습','관심사에 맞는 뉴스 교재']};
const mobile={ja:{columns:['比較項目','AI発音','添削型','Lanclo'],features:[['自分の声の','お手本'],['発音','チェック'],['結果に合う','次の練習'],['興味に合う','ニュース']]},en:{columns:['Feature','AI apps','Human review','Lanclo'],features:[['Own-voice','model'],['Pronunciation','feedback'],['Adaptive','practice'],['Personal','news']]},ko:{columns:['비교 항목','AI 발음','첨삭형','Lanclo'],features:[['내 목소리','예시'],['발음','피드백'],['결과 맞춤','연습'],['관심사','뉴스']]}};
export default function Comparison({lang}){const c=content[lang];const order=[0,3,1,2];const symbols=[['○','△','—'],['○','○','○'],['○','○','○'],['○','—','—']];return <section id="comparison" className="section wrap comparison-section"><div className="section-heading"><h2>{c.title}</h2></div><div className="comparison-scroll" tabIndex="0" role="region" aria-label={c.title.replace('\n',' ')}><table><thead><tr>{order.map(i=><th key={i} scope="col" className={i===3?'lanclo-column':''}><span className="comparison-wide-label">{c.columns[i]}</span><span className="comparison-mobile-label" aria-hidden="true">{mobile[lang].columns[i]}</span></th>)}</tr></thead><tbody>{c.rows.map((row,r)=><tr key={row[0]}><th scope="row"><span className="comparison-wide-label">{features[lang][r]}</span><span className="comparison-mobile-label" aria-hidden="true">{mobile[lang].features[r].map(part=><span key={part}>{part}</span>)}</span></th>{[3,1,2].map((i,column)=><td key={i} className={i===3?'lanclo-column':''}><span className="comparison-symbol">{symbols[r][column]}</span><small>{row[i]}</small></td>)}</tr>)}</tbody></table></div><p className="comparison-legend">{legends[lang].split('　').map(item=><span key={item}>{item}</span>)}</p><p className="comparison-note"><ReadableText>{c.note}</ReadableText></p></section>}
