const researchUrls = {
  voice: 'https://www.isca-archive.org/slate_2025/yamanaka25_slate.html',
  instruction: 'https://onlinelibrary.wiley.com/doi/10.1111/lang.12345',
  asr: 'https://www.cambridge.org/core/journals/recall/article/effectiveness-of-automatic-speech-recognition-in-eslefl-pronunciation-a-metaanalysis/A915444CF252B61D14961D2FE733822D',
  clone: 'https://onlinelibrary.wiley.com/doi/10.1111/ijal.70014',
  counter: 'https://www.isca-archive.org/interspeech_2021/silpachai21_interspeech.html',
}

export const copy = {
  ja: {
    nav: ['自分の声', '個別レッスン', 'ニュース', '研究'],
    login: '練習に戻る',
    cta: '自分の声ではじめる',
    eyebrow: '英語の発音を、もう一歩。',
    hero: '憧れの発音を、\n自分の声で。',
    intro: '自分の声のお手本を聴く。苦手に合わせて、一文ずつ練習する。気になるニュースも、英語で楽しむ。',
    discover: 'Lancloでできること',
    pillars: ['自分の声がお手本に', '練習の結果が次のレッスンに', '興味のあるニュースも教材に'],
    voiceTitle: '目指す自分の英語を、\n先に聴く。',
    voiceBody: '録音した声から、英語のお手本をつくります。自分の声で、こんなふうに話してみたい。その響きを聴いて、まねして、練習する。',
    voiceSteps: ['自分の声を録音する', '自分のAIボイスをつくる', 'その声のお手本で練習する'],
    founderQuote: 'シャドーイングで、自分に似た声のお手本を探すのが大変でした。海外で暮らしていても、発音が伝わらないことがある。自分が目指す英語を、自分の声で聴いてみたい。それが、Lancloの始まりです。',
    founderLabel: 'Lancloをつくった理由',
    lessonTitle: '練習の結果が、\n次のレッスンをつくる。',
    lessonBody: '発音、リズム、抑揚を録音ごとに確認。今の強みと磨きたい音をもとに、次のレッスンを組み立てます。',
    lessonLabels: ['話してみる', '磨くところを知る', '次の練習へ'],
    lessonPanels: [
      { title: 'まずは、一文。', body: 'お手本を聴いて、自分でも話してみる。録音はその場で聴き返せます。', detail: '聴く → 録音する → 聴き比べる' },
      { title: '「th」の音を、もう少し。', body: 'たとえば /θ/ は、舌先を上下の歯の間に軽く置き、声を出さずに息を通します。', detail: 'thought · worth ／ フィードバックの例' },
      { title: '磨きたい音を、次の一文に。', body: '練習結果をもとに、次のレッスンを構成。一文ずつ、お手本と自分の録音を確かめます。', detail: '結果に合う練習 → もう一度録音' },
    ],
    sampleLabel: '練習画面の紹介用サンプル',
    newsTitle: '知りたいことが、\n英語を続ける理由に。',
    newsBody: '興味のあるテーマから記事を選ぶ。自分の声のお手本で聴いて、気になる一文を練習する。知りたいことが、英語に触れるきっかけになります。',
    newsTopics: ['テクノロジー', 'カルチャー', '旅', 'サイエンス'],
    newsArticles: [
      { title: '人とテクノロジーの、これから。', body: '新しい道具が、暮らしをどう変えるのか。身近な問いから英語に触れる。' },
      { title: '世界の暮らしを、のぞいてみる。', body: '食、音楽、街の文化。まだ知らない日常を、英語で楽しむ。' },
      { title: '次に行きたい街を、英語で。', body: '知らない場所の魅力や暮らし方を、旅する気持ちで読む。' },
      { title: '「なぜ？」から広がる世界。', body: '自然や宇宙の不思議を題材に、好奇心のまま英語を読む。' },
    ],
    newsNote: 'テーマと文章は紹介用サンプルです。実際の記事・掲載日はアプリで確認できます。',
    researchTitle: '自分の声で学ぶ。\n研究が示す可能性。',
    researchIntro: '「自分の声をお手本にする」発想を支える、2つの研究。',
    studies: [
      { number: '15', unit: '人の模倣実験', title: '自分が聞き慣れた声を、お手本に。', body: '普段自分に聞こえる声に近づけたお手本を使う研究。参加者の好みと、発音の一部をより正確にまねる結果が報告されました。', limit: '小規模・短期の実験です。通常の録音クローンとは方式が異なり、Lancloや長期の上達を検証したものではありません。', source: 'Yamanaka et al. · SLaTE 2025', url: researchUrls.voice },
      { number: '77', unit: '研究のメタ分析', title: '磨くところを決めて、発音を練習する。', body: '2,573人を含む発音指導の研究を統合。特定の音やリズムに意識を向ける課題で、指導による改善が報告されています。', limit: '発音指導一般の研究です。自声の効果を示すものではなく、自由な会話全体への効果はまだ明確ではありません。', source: 'Saito & Plonsky · Language Learning 2019', url: researchUrls.instruction },
    ],
    moreResearch: 'ほかの研究と、わかっていないこと',
    otherStudies: [
      { title: '発音指導の効果 · 77研究・2,573人', body: 'Saito & Plonsky（2019）は発音指導による改善を報告。特定の音やリズムに焦点を当てた課題で効果が明確でした。自分の声の効果を調べた研究ではありません。', url: researchUrls.instruction },
      { title: '音声認識を使う発音練習 · 2024', body: '15の実験・準実験をまとめた研究では、音声認識を使う練習の効果が報告されています。Lancloの生成AIによる評価精度を検証した研究ではありません。', url: researchUrls.asr },
      { title: 'AIでつくった自声による練習 · 2026', body: '21人・8週間の研究で、練習後の流暢さと理解しやすさの改善が報告されています。別のツールを用いた小規模研究で、Lancloの効果実証ではありません。', url: researchUrls.clone },
      { title: '自分の声なら、いつでも有利？ · 2021', body: '自声と他声を比べた2つの実験では、自声によって子音・母音の誤りを見つけやすくなる効果は確認されませんでした。自声であれば常に有利とは限りません。', url: researchUrls.counter },
    ],
    faqTitle: 'はじめる前に',
    faqs: [
      { q: '自分の声がお手本になるのですか？', a: '本人の同意のもとで録音した声から、AIボイスのお手本をつくります。本人が実際に話した音声とは異なります。声の似方や発音は、録音や生成の条件によって変わります。' },
      { q: '発音の評価で、何がわかりますか？', a: '発音、リズム、抑揚などの練習結果と、改善のヒントを確認できます。AIによる学習の目安であり、資格試験のスコアや正確さを保証する判定ではありません。' },
      { q: 'ニュースはどうやって練習しますか？', a: '興味のあるテーマから記事を選び、自分の声のお手本を聴きながら一文ずつ練習できます。記事は、あなた専用に事実を書き換えるものではありません。' },
      { q: '録音した声はどう使われますか？', a: '声のお手本の作成や、同意した発音評価に使います。音声は必要な処理のため外部サービスへ送信されます。録音前の同意画面で、利用目的や保存について確認できます。' },
    ],
    finalTitle: 'こんなふうに話す自分を、\n聴いてみよう。',
    finalBody: '自分の声のお手本と、今の自分に合う練習から。',
    footer: '自分の声で、英語の発音を磨く。',
    privacy: 'プライバシー',
    terms: '利用規約',
  },
  en: {
    nav: ['Your voice', 'Your lessons', 'News', 'Research'],
    login: 'Continue practicing',
    cta: 'Start with your voice',
    eyebrow: 'Take your English pronunciation further.',
    hero: 'Your voice.\nThe English you want to speak.',
    intro: 'Hear a model in your own voice. Practice the sounds that need work, one sentence at a time. Explore the news that interests you.',
    discover: 'Meet Lanclo',
    pillars: ['Your voice as a model', 'Practice shaped by your results', 'News that feeds your curiosity'],
    voiceTitle: 'Hear the English\nyou want to speak.',
    voiceBody: 'Turn a recording of your voice into a pronunciation model. Hear what you want to work toward in a voice that sounds like you. Listen, repeat, and practice.',
    voiceSteps: ['Record your voice', 'Create your AI voice', 'Practice with your voice as a model'],
    founderQuote: 'When I practiced shadowing, finding a speaker with a voice like mine was hard. Even living abroad, my pronunciation sometimes got in the way. I wanted to hear the English I was working toward in my own voice. That is where Lanclo began.',
    founderLabel: 'Why we made Lanclo',
    lessonTitle: 'Your practice shapes\nyour next lesson.',
    lessonBody: 'Get feedback on pronunciation, rhythm, and intonation as you record. Your strengths and the sounds that need work help shape your next lesson.',
    lessonLabels: ['Say it', 'Find your focus', 'Practice what comes next'],
    lessonPanels: [
      { title: 'Start with one sentence.', body: 'Listen to the model, then say it yourself. Play your recording back right where you practiced.', detail: 'Listen → Record → Compare' },
      { title: 'Give “th” a little attention.', body: 'For /θ/, rest the tip of your tongue lightly between your teeth and let air flow through without using your voice.', detail: 'thought · worth / Example feedback' },
      { title: 'Bring that sound into your next sentence.', body: 'Your results help shape the next lesson. Practice one sentence at a time and compare the model with your recording.', detail: 'Focused practice → Record again' },
    ],
    sampleLabel: 'Illustrative practice example',
    newsTitle: 'News you care about.\nEnglish in your own voice.',
    newsBody: 'Choose an article on a topic you love. Listen in your own voice, then practice a sentence that catches your attention. Let curiosity give you a reason to keep going.',
    newsTopics: ['Technology', 'Culture', 'Travel', 'Science'],
    newsArticles: [
      { title: 'How technology shapes our lives', body: 'Explore the tools changing everyday life, and the questions they raise.' },
      { title: 'A glimpse of life somewhere else', body: 'Food, music, and local traditions. Discover everyday stories in English.' },
      { title: 'Where would you go next?', body: 'Get to know a place through its streets, its people, and their stories.' },
      { title: 'Follow a good question', body: 'From the natural world to outer space, let curiosity lead your reading.' },
    ],
    newsNote: 'Topics and text are illustrative examples. See the app for available articles and publication dates.',
    researchTitle: 'Learning with your own voice.\nThe research behind the idea.',
    researchIntro: 'Two studies that inform the idea of learning with your own voice.',
    studies: [
      { number: '15', unit: 'participants', title: 'A model closer to the voice you hear as your own.', body: 'Researchers adjusted model voices to resemble learners’ self-perceived voices. They reported learner preference and more accurate imitation of some pronunciation features.', limit: 'A small, short-term experiment using a different method from ordinary voice cloning. It did not test Lanclo or long-term learning.', source: 'Yamanaka et al. · SLaTE 2025', url: researchUrls.voice },
      { number: '77', unit: 'studies reviewed', title: 'Give pronunciation a clear focus.', body: 'A review covering 2,573 learners found gains from pronunciation instruction, particularly on tasks focused on specific sounds or prosody.', limit: 'Research on pronunciation instruction in general, not own-voice models. Effects on overall spontaneous speech remain less clear.', source: 'Saito & Plonsky · Language Learning 2019', url: researchUrls.instruction },
    ],
    moreResearch: 'More research, including its limits',
    otherStudies: [
      { title: 'Pronunciation instruction · 77 studies, 2,573 learners', body: 'Saito & Plonsky (2019) found gains from instruction, clearest in tasks focused on sounds or prosody. This is not evidence of an own-voice advantage.', url: researchUrls.instruction },
      { title: 'Speech recognition in pronunciation practice · 2024', body: 'A review of 15 experiments and quasi-experiments reported benefits from speech-recognition-assisted practice. It does not establish the accuracy of Lanclo’s generative AI feedback.', url: researchUrls.asr },
      { title: 'Practice with an AI-cloned voice · 2026', body: 'A study of 21 learners over eight weeks reported gains in fluency and comprehensibility after practice. It used another tool and does not establish Lanclo’s effectiveness.', url: researchUrls.clone },
      { title: 'Is your own voice always better? · 2021', body: 'Two experiments comparing own-voice and other-voice models did not find an own-voice advantage in detecting consonant and vowel errors. Using your own voice is not automatically better.', url: researchUrls.counter },
    ],
    faqTitle: 'Before you begin',
    faqs: [
      { q: 'Will the model sound like me?', a: 'With your consent, Lanclo creates an AI voice from your recording. The model is generated audio, not a recording of you saying those words. Voice similarity and pronunciation vary with recording and generation conditions.' },
      { q: 'What does pronunciation feedback tell me?', a: 'It offers practice feedback on pronunciation, rhythm, intonation, and areas to work on. It is an AI learning aid, not an official test score or a guaranteed judgment of accuracy.' },
      { q: 'How do I practice with news?', a: 'Choose an article from topics that interest you, listen to a model in your own voice, and practice sentence by sentence. Personalization does not mean rewriting the facts of a story for you.' },
      { q: 'How is my voice used?', a: 'Your recordings are used to create your voice model and for pronunciation feedback you consent to. Audio is sent to external services for the necessary processing. Review the consent screen for details about use and storage before recording.' },
    ],
    finalTitle: 'Hear the English\nyou want to speak.',
    finalBody: 'Start with your voice, and practice that meets you where you are.',
    footer: 'English pronunciation practice, in your own voice.',
    privacy: 'Privacy',
    terms: 'Terms',
  },
  ko: {
    nav: ['내 목소리', '맞춤 레슨', '뉴스', '연구'],
    login: '연습으로 돌아가기',
    cta: '내 목소리로 시작하기',
    eyebrow: '영어 발음, 한 걸음 더.',
    hero: '내 목소리로 듣는,\n말하고 싶던 영어.',
    intro: '내 목소리로 된 발음 예시를 듣고, 부족한 부분을 한 문장씩 연습하세요. 관심 있는 뉴스도 영어로 만나보세요.',
    discover: 'Lanclo 알아보기',
    pillars: ['내 목소리로 듣는 발음 예시', '연습 결과에 맞춘 다음 레슨', '관심 있는 뉴스로 이어가는 연습'],
    voiceTitle: '말하고 싶던 영어를,\n내 목소리로 먼저 들어보세요.',
    voiceBody: '녹음한 목소리로 영어 발음 예시를 만듭니다. 나도 이렇게 말하고 싶다는 마음이 들도록. 익숙한 목소리를 듣고, 따라 말하고, 연습해 보세요.',
    voiceSteps: ['내 목소리 녹음하기', '나만의 AI 음성 만들기', '내 목소리의 발음 예시로 연습하기'],
    founderQuote: '쉐도잉을 할 때 나와 목소리가 비슷한 사람을 찾기가 어려웠습니다. 해외에 살면서도 발음 때문에 말이 통하지 않을 때가 있었어요. 내가 목표로 하는 영어를 내 목소리로 듣고 싶었습니다. Lanclo는 그렇게 시작됐습니다.',
    founderLabel: 'Lanclo를 만든 이유',
    lessonTitle: '연습 결과가\n다음 레슨을 만듭니다.',
    lessonBody: '녹음할 때마다 발음, 리듬, 억양을 확인하세요. 잘하는 부분과 다듬어야 할 발음을 바탕으로 다음 레슨을 구성합니다.',
    lessonLabels: ['직접 말하기', '연습할 부분 찾기', '다음 연습으로'],
    lessonPanels: [
      { title: '한 문장부터 시작하세요.', body: '발음 예시를 듣고 직접 말해 보세요. 녹음한 목소리는 그 자리에서 다시 들을 수 있습니다.', detail: '듣기 → 녹음하기 → 비교하기' },
      { title: '“th” 발음을 조금 더 다듬어 보세요.', body: '/θ/는 혀끝을 위아래 치아 사이에 가볍게 대고, 목소리를 내지 않은 채 바람을 내보내는 소리입니다.', detail: 'thought · worth / 피드백 예시' },
      { title: '연습할 발음을 다음 문장으로.', body: '연습 결과를 바탕으로 다음 레슨을 구성합니다. 한 문장씩 연습하며 발음 예시와 내 녹음을 비교해 보세요.', detail: '필요한 발음 연습 → 다시 녹음하기' },
    ],
    sampleLabel: '연습 화면을 소개하기 위한 예시',
    newsTitle: '궁금한 뉴스가,\n내 목소리로 하는 영어 연습으로.',
    newsBody: '관심 있는 주제에서 기사를 고르세요. 내 목소리로 듣고, 눈길이 가는 문장을 연습해 보세요. 알고 싶은 이야기가 영어를 만나는 계기가 됩니다.',
    newsTopics: ['테크놀로지', '문화', '여행', '과학'],
    newsArticles: [
      { title: '기술은 일상을 어떻게 바꿀까요?', body: '새로운 도구와 우리 삶의 변화를, 친숙한 질문에서부터 살펴봅니다.' },
      { title: '다른 나라의 일상을 들여다보세요.', body: '음식과 음악, 지역의 문화. 아직 몰랐던 이야기를 영어로 만나보세요.' },
      { title: '다음에는 어느 도시로 떠날까요?', body: '낯선 도시의 거리와 사람들의 삶을 여행하는 마음으로 읽어보세요.' },
      { title: '“왜?”라는 질문에서 시작하는 세계.', body: '자연부터 우주까지, 호기심이 이끄는 대로 영어를 읽어보세요.' },
    ],
    newsNote: '주제와 문장은 소개용 예시입니다. 실제 기사와 발행일은 앱에서 확인할 수 있습니다.',
    researchTitle: '내 목소리로 배우는 영어.\n연구에서 찾은 가능성.',
    researchIntro: '내 목소리를 발음 예시로 사용하는 아이디어에 참고한 두 연구.',
    studies: [
      { number: '15', unit: '명의 모방 실험', title: '스스로 듣는 목소리에 가까운 발음 예시.', body: '학습자가 평소 듣는 자기 목소리에 가깝게 조정한 음성을 연구했습니다. 참여자의 선호와 일부 발음을 더 정확하게 모방한 결과가 보고됐습니다.', limit: '소규모·단기 실험이며 일반적인 음성 복제와 방식이 다릅니다. Lanclo나 장기적인 학습 효과를 검증한 연구는 아닙니다.', source: 'Yamanaka et al. · SLaTE 2025', url: researchUrls.voice },
      { number: '77', unit: '개 연구의 메타분석', title: '연습할 발음을 정하고, 집중해서 배우기.', body: '학습자 2,573명이 포함된 연구를 종합했습니다. 특정 소리나 운율에 집중하는 과제에서 발음 지도의 효과가 보고됐습니다.', limit: '발음 지도 전반에 관한 연구로, 자기 목소리의 효과를 입증하지는 않습니다. 자유로운 대화 전반에 미치는 효과는 아직 명확하지 않습니다.', source: 'Saito & Plonsky · Language Learning 2019', url: researchUrls.instruction },
    ],
    moreResearch: '다른 연구와 아직 밝혀지지 않은 점',
    otherStudies: [
      { title: '발음 지도 · 77개 연구, 2,573명', body: 'Saito & Plonsky (2019)는 특정 소리나 운율에 초점을 둔 과제에서 발음 지도의 개선 효과를 보고했습니다. 자기 목소리의 효과를 검증한 연구는 아닙니다.', url: researchUrls.instruction },
      { title: '음성 인식을 활용한 발음 연습 · 2024', body: '15개의 실험·준실험을 종합한 연구에서 음성 인식을 활용한 연습의 효과가 보고됐습니다. Lanclo의 생성형 AI 평가 정확도를 검증한 연구는 아닙니다.', url: researchUrls.asr },
      { title: 'AI로 복제한 목소리를 활용한 연습 · 2026', body: '21명이 8주간 참여한 연구에서 연습 후 유창성과 이해 용이성이 개선됐다고 보고됐습니다. 다른 도구를 사용한 소규모 연구로, Lanclo의 효과를 입증하지는 않습니다.', url: researchUrls.clone },
      { title: '내 목소리가 언제나 더 좋을까요? · 2021', body: '자기 목소리와 다른 사람의 목소리를 비교한 두 실험에서, 자기 목소리가 자음·모음의 오류를 찾는 데 더 유리하다는 결과는 확인되지 않았습니다. 내 목소리라고 항상 더 좋은 것은 아닙니다.', url: researchUrls.counter },
    ],
    faqTitle: '시작하기 전에',
    faqs: [
      { q: '내 목소리가 발음 예시가 되나요?', a: '본인의 동의를 받아 녹음한 목소리로 AI 음성을 만듭니다. 본인이 실제로 해당 문장을 말한 녹음과는 다릅니다. 목소리의 유사도와 발음은 녹음 및 생성 조건에 따라 달라집니다.' },
      { q: '발음 평가로 무엇을 알 수 있나요?', a: '발음, 리듬, 억양에 대한 연습 결과와 개선을 위한 힌트를 확인할 수 있습니다. AI가 제공하는 학습 참고 자료이며, 공인 시험 점수나 정확성을 보장하는 판정은 아닙니다.' },
      { q: '뉴스로 어떻게 연습하나요?', a: '관심 있는 주제에서 기사를 고르고 내 목소리로 된 발음 예시를 들으며 한 문장씩 연습할 수 있습니다. 맞춤형 학습을 위해 기사의 사실을 개인별로 바꾸지는 않습니다.' },
      { q: '녹음한 목소리는 어떻게 사용되나요?', a: '내 목소리의 발음 예시를 만들거나, 동의한 발음 평가에 사용됩니다. 필요한 처리를 위해 음성이 외부 서비스로 전송됩니다. 녹음 전 동의 화면에서 이용 목적과 저장에 관한 내용을 확인할 수 있습니다.' },
    ],
    finalTitle: '말하고 싶던 영어를,\n내 목소리로 들어보세요.',
    finalBody: '내 목소리의 발음 예시와 지금 나에게 맞는 연습부터.',
    footer: '내 목소리로 다듬는 영어 발음.',
    privacy: '개인정보 처리방침',
    terms: '이용약관',
  },
}
