import ReadableText from './ReadableText.jsx';
import React from 'react';
import {motion,useReducedMotion} from 'motion/react';
import {ArrowRight,Microphone,SpeakerHigh} from '@phosphor-icons/react';
import LessonRadar from '../pronunciation/LessonRadar.jsx';
import NewsCarousel from './NewsCarousel.jsx';
import NewsDevices from './NewsDevices.jsx';
import NewsPersonalization from './NewsPersonalization.jsx';
import {narrative} from './narrative.js';

const demoDimensions=Object.freeze({sounds:64,stress:82,rhythm:70,intonation:85,fluency:78});
const text={ja:{result:'発音を、5つの視点で。',focus:'次に磨く音',next:'この音を、次のレッスンでも。',sound:'「th」の音を、もう少し。',note:'数値・指摘は表示例です。実際の分析結果や上達実績ではありません。',reading:'気になる一文から、声に出す。',sample:'教材のイメージ',sync:'同じアカウントでログイン。保存を停止した場合は再開が必要です。ゲストのデータは別途移行します。',chartTitle:'お手本との「声の高低の動き」の一致',chartUnit:'ピッチ相関 / 0〜1・高いほど一致',bars:['本人の声に合わせたお手本','同性の他者の声','異性の他者の声'],chartNote:'日本語話者15人。本人声は録音型・自己知覚調整型の2条件を統合。短期の模倣実験であり、Lancloや長期の上達を測定した結果ではありません。',studyTitle:'自分に合う声で、抑揚をまねやすく。',studyBody:'本人の声に合わせた条件で、お手本の抑揚との高い一致が報告されました。',metaTitle:'磨く音を決めて、練習する。',metaKicker:'77研究・2,573人のメタ分析',metaBody:'特定の音やリズムに意識を向ける課題で、発音指導による改善が報告されています。',metaSteps:['磨く音を決める','意識して練習する','発音を確かめる']},en:{result:'Five dimensions of your pronunciation.',focus:'Your next focus',next:'Take this sound into your next lesson.',sound:'Give “th” a little attention.',note:'Scores and feedback are illustrative demo data, not measured results or evidence of improvement.',reading:'Find a sentence. Make it yours.',sample:'Illustrative learning example',sync:'Sign in with the same account. Resume saving if you previously turned it off. Guest data requires a separate transfer.',chartTitle:'Matching the pitch movement of the model',chartUnit:'Pitch correlation / 0–1; higher means closer',bars:['Own-voice model conditions','Same-gender other voice','Different-gender other voice'],chartNote:'15 Japanese speakers. Own-voice results combine recorded and self-perceived voice conditions. A short-term imitation study, not a test of Lanclo or long-term learning.',studyTitle:'A familiar voice. Closer pitch imitation.',studyBody:'The own-voice conditions showed closer pitch matching to the model.',metaTitle:'Choose a sound. Give it focused practice.',metaKicker:'77 studies · 2,573 learners',metaBody:'Pronunciation instruction showed gains, especially in tasks focused on particular sounds or prosody.',metaSteps:['Find a focus','Practice intentionally','Check your pronunciation']},ko:{result:'발음을 다섯 가지 관점으로.',focus:'다음 연습의 초점',next:'이 발음을 다음 레슨에서도.',sound:'“th” 발음을 조금 더.',note:'점수와 피드백은 데모 데이터이며 실제 측정 결과나 향상 실적이 아닙니다.',reading:'관심 있는 한 문장을, 소리 내어.',sample:'학습 화면 예시',sync:'같은 계정으로 로그인하세요. 저장을 중지했다면 다시 시작해야 합니다. 게스트 데이터는 별도로 이전합니다.',chartTitle:'발음 예시와 목소리 높낮이의 일치',chartUnit:'피치 상관계수 / 0–1, 높을수록 유사',bars:['본인 목소리 기반 예시','동성 타인의 목소리','이성 타인의 목소리'],chartNote:'일본어 화자 15명. 본인 목소리는 녹음형과 자기지각 조정형 두 조건을 합친 결과입니다. 단기 모방 실험으로 Lanclo나 장기 학습 효과를 검증하지 않았습니다.',studyTitle:'익숙한 목소리로, 억양을 더 가깝게.',studyBody:'본인 목소리 기반 조건에서 예시의 높낮이와 더 높은 일치가 보고되었습니다.',metaTitle:'연습할 소리에 집중하세요.',metaKicker:'77개 연구 · 2,573명',metaBody:'특정 소리나 운율에 집중하는 과제에서 발음 지도의 개선 효과가 보고되었습니다.',metaSteps:['연습할 소리 선택','집중해서 연습','발음 확인']}};
function Enter({children,className='',delay=0}){const reduce=useReducedMotion();return <motion.div className={className} initial={reduce?false:{opacity:0,y:24}} animate={reduce?{opacity:1,y:0}:undefined} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{duration:reduce?0:.6,delay:reduce?0:delay,ease:[.2,.7,.2,1]}}>{children}</motion.div>}
const lessonFlow={
 ja:{title:'次に何を練習するか、\nもう迷わない。',intro:'発音の指摘と練習履歴から、復習する文と次に挑戦する文を選ぶ。AIがあなた向けにレッスンを組み立てます。',titles:['まず、一文話す。','AIが、苦手な音を見つける。','次は、その音を練習。'],bodies:['お手本を聴いて、自分の声を録音します。','発音・リズム・抑揚などを分析。どこを、どう直すかがわかります。','指摘された言葉や練習履歴をもとに、候補の英文から次の練習を組み立てます。'],record:'自分の声を録音',found:'今回の練習ポイント：th /θ/',tip:'舌先を歯の間に軽く置き、声を出さずに息を通します。',next:'「th」を含む、次の練習例',voice:'自分の声のお手本で、もう一度。',loop:'練習する → フィードバック → 次のレッスン。話すたびに、このサイクルが続きます。'},
 en:{title:'Let AI plan the practice.\nYou focus on speaking.',intro:'Feedback and practice history help select what to review and what to try next. AI assembles a lesson for you.',titles:['Say a sentence.','AI finds a focus.','Practice it in your next lesson.'],bodies:['Listen to the model, then record your own voice.','Review sounds, rhythm and intonation, with a concrete adjustment to try.','AI selects the next practice from available sentences, using feedback on specific words and your history.'],record:'Record your voice',found:'Practice focus: th /θ/',tip:'Place your tongue tip gently between your teeth and let air flow without voicing.',next:'A next-practice example with “th”',voice:'Hear the model in your own voice. Try again.',loop:'Practice → feedback → your next lesson. Keep the cycle going with every attempt.'},
 ko:{title:'문제 선택은 AI에게.\n나는 한 문장씩 말해요.',intro:'발음 피드백과 연습 기록을 바탕으로 복습할 문장과 다음에 도전할 문장을 골라 레슨을 구성합니다.',titles:['먼저, 한 문장을 말해요.','AI가 연습할 발음을 찾아요.','다음 레슨에서 연습해요.'],bodies:['발음 예시를 듣고 내 목소리를 녹음하세요.','발음·리듬·억양을 분석해 바꿔 볼 부분을 알려 줍니다.','단어별 피드백과 연습 기록을 바탕으로 준비된 문장 중 다음 연습을 구성합니다.'],record:'내 목소리 녹음',found:'이번 연습의 초점: th /θ/',tip:'혀끝을 치아 사이에 가볍게 두고 목소리 없이 공기를 내보내세요.',next:'“th”가 포함된 다음 연습 예시',voice:'내 목소리의 예시를 듣고 다시 연습해요.',loop:'연습 → 피드백 → 다음 레슨. 말할 때마다 이 과정을 이어갑니다.'}
};
export function LessonExperience({lang,compact=false}){
 const c=text[lang],f=lessonFlow[lang];
 return <section id="lessons" className="lesson-story lesson-step-story section"><div className="wrap"><Enter className="section-heading"><h2>{compact?({ja:"苦手がわかる。\n次の練習が変わる。",en:"Find your focus.\nShape your next practice.",ko:"어려운 소리를 알고,\n다음 연습이 달라져요."}[lang]):f.title}</h2><p>{compact?({ja:"発音・アクセント・リズム・抑揚・流暢さ。5つの視点で、次に磨く音を見つけます。",en:"Sounds, stress, rhythm, intonation and fluency. Five perspectives on what to practice next.",ko:"발음·강세·리듬·억양·유창성. 다섯 가지 관점으로 다음에 연습할 소리를 찾아요."}[lang]):f.intro}</p></Enter>
 <ol className="lesson-steps">{f.titles.slice(0,compact?2:3).map((title,i)=><li data-lesson-scene={i} key={title}><Enter>
 <div className="lesson-step-number"><span>0{i+1}</span>{i<2&&<ArrowRight size={22} aria-hidden="true"/>}</div>

 <h3>{title}</h3><p className="lesson-step-body"><ReadableText>{f.bodies[i]}</ReadableText></p>
 {i===0?<div className="lesson-step-output"><span className="step-output-label">{f.record}</span><p className="step-phrase" lang="en">I <mark>thought</mark> it was worth a try.</p><span className="step-microphone" aria-hidden="true"><Microphone size={28}/></span></div>:i===1?<div className="lesson-step-output analysis-example"><span className="step-output-label">{f.found}</span><div className="step-radar" lang={lang==='ja'?'ja':'en'}><LessonRadar dimensions={demoDimensions} score={76} ui={lang==='ja'?'ja':'en'}/></div><div className="feedback-link"><span>{lang==='ja'?'言葉ごとのフィードバック例':lang==='ko'?'단어별 피드백 예시':'Word-level feedback example'}</span><strong lang="en">thought · worth <b>/θ/</b></strong><p className="step-tip">{f.tip}</p></div><p className="example-note">{c.note}</p></div>:<div className="lesson-step-output next-output"><span className="step-output-label">{f.next}</span><p className="step-phrase" lang="en">I <mark>think</mark> the meeting starts at <mark>three</mark>.</p><div className="next-practice-set"><span>{lang==='ja'?'別の文でも、同じ音を。':lang==='ko'?'다른 문장에서도 같은 소리를.':'The same sound in another sentence.'}</span><div lang="en">Please put the books on the <mark>third</mark> shelf.</div><small>{lang==='ja'?'候補教材から構成する練習例':lang==='ko'?'준비된 교재로 구성한 연습 예시':'Example drawn from available practice material'}</small></div><div className="step-own-voice"><SpeakerHigh size={22}/><small>{f.voice}</small></div></div>}
 </Enter></li>)}</ol>{!compact&&<p className="lesson-cycle">{f.loop}</p>}</div></section>;
}
export function NewsExperience({lang}){const n=narrative[lang];return <section id="news" className="section news-story news-compact"><div className="wrap"><div className="news-compact-top"><Enter className="section-heading"><h2>{lang==='ja'?<><span className="phrase">あなたの「好き」が、</span><span className="phrase">英語の教材になる。</span></>:n.newsTitle}</h2><p>{lang==='ja'?'AIが、ニュースを英語教材に。':lang==='ko'?'AI가 뉴스를 영어 교재로.':'AI turns news into English practice.'}</p><NewsPersonalization lang={lang}/></Enter><Enter><NewsDevices lang={lang}/></Enter></div></div><NewsCarousel lang={lang}/></section>}
