export const narrative = {
  ja: {
    heroTitle: 'ネイティブのように。\nあなたの声で。',
    heroIntro: 'あなたの声をもとに、目指す発音・リズムのお手本をつくる。聴いて、話して、違いを確かめる。練習の結果は、次の個別レッスンへ。',
    voiceTitle: '声は、あなたらしく。\n発音は、目指す響きへ。',
    voiceIntro: '録音からつくるのは、自分の声に似た英語のお手本。どんな発音やリズムを目指したいか、自分の録音と聴き比べながら練習できます。',
    inputLabel: 'いまの自分の録音',
    outputLabel: 'あなたの声のAIお手本',
    voiceCaption: '声の個性をもとに、発音・リズムのお手本へ。',
    lessonTitle: '練習の結果で、\n次の一文が変わる。',
    lessonIntro: '発音・アクセント・リズム・抑揚・流暢さを、5つの軸で確認。磨きたい音と練習の履歴を、次のレッスンに生かします。',
    lessonSteps: [
      { title: '磨きたい音を見つける。', body: 'たとえば thought と worth の /θ/。どの言葉の、どの音を練習するかが見えてきます。' },
      { title: 'どう変えるかが、わかる。', body: '舌先を上下の歯の間に軽く置き、声を出さずに息を通す。具体的なヒントを、次の発音で試します。' },
      { title: 'その音を、次の一文でも。', body: '結果に合わせて、次のレッスンを構成。お手本を聴き、新しい文の中でも同じ音を練習します。' },
    ],
    lessonSampleLabel: '実際の採点UI · デモデータ',
    lessonNextLabel: '次のレッスン',
    newsTitle: 'あなたの「好き」が、英語の教材になる。',
    newsIntro: 'AIが記事を英語教材に。興味のある話題と難しさを選んで、あなたの声のお手本で練習できます。',
    newsStages: [
      { title: '好きな話題から。', body: 'テクノロジー、カルチャー、旅、サイエンス。興味のあるテーマを選びます。' },
      { title: '気になる記事を読む。', body: '世界の出来事を英語で読む。目に留まった一文が、今日の練習になります。' },
      { title: 'あなたの声で、練習する。', body: '自分の声のお手本を聴いて、録音してみる。記事の中の英語を、自分でも声に出してみましょう。' },
    ],
    newsSampleTitle: '歩いて楽しむ街の、小さな工夫。',
    newsSampleSentence: 'An AI agent can score well on familiar tests and still struggle with a new task.',
    newsSampleNote: '記事と英文は、練習の流れを紹介するための例です。',
    devicesTitle: 'スマホでも、PCでも。\nいつもの声で、\n練習の続きへ。',
    devicesIntro: '同じアカウントでログインすれば、保存した自分の声、練習履歴、録音を別の端末でも。使いやすい画面で、続きを始められます。',
    deviceLabels: ['パソコン', 'スマートフォン', 'タブレット'],
    researchTitle: '自分の声で学ぶ。\n研究が示す可能性。',
  },
  en: {
    heroTitle: 'Imagine speaking like a native.\nHear it in your own voice.',
    heroIntro: 'Create a model of the pronunciation and rhythm you want to work toward, in a voice that sounds like you. Listen, speak, and compare. Let your practice shape your next lesson.',
    voiceTitle: 'A voice like yours.\nA sound to work toward.',
    voiceIntro: 'Your recording becomes an English pronunciation model in a voice like your own. Compare it with what you said, then practice the sounds and rhythm you want to develop.',
    inputLabel: 'Your original recording',
    outputLabel: 'Your AI voice model',
    voiceCaption: 'Your voice, reimagined as a pronunciation model.',
    lessonTitle: 'What you practice today\nshapes your next sentence.',
    lessonIntro: 'See feedback across five areas: pronunciation, word stress, rhythm, intonation, and fluency. The sounds that need work and your practice history help shape your next lesson.',
    lessonSteps: [
      { title: 'Find the sound to work on.', body: 'Take /θ/ in thought and worth. Feedback helps you see which sound, in which word, deserves your attention.' },
      { title: 'Know what to try.', body: 'Rest the tip of your tongue lightly between your teeth and let air flow through without using your voice. Put a specific tip into practice.' },
      { title: 'Meet that sound in another sentence.', body: 'Your results help shape the next lesson. Listen to the model, then practice the same sound in a new sentence.' },
    ],
    lessonSampleLabel: 'Actual assessment interface · Demo data',
    lessonNextLabel: 'Your next lesson',
    newsTitle: 'Your interests. Your English practice.',
    newsIntro: 'Hear an article that interests you in your own voice, then practice it one sentence at a time. Give your curiosity a place in your English practice.',
    newsStages: [
      { title: 'Start with your interests.', body: 'Technology, culture, travel, or science. Choose the topics you want to explore.' },
      { title: 'Find a story worth reading.', body: 'Read about the world in English. A sentence that catches your attention can become today’s practice.' },
      { title: 'Make time to say it yourself.', body: 'Listen to the model in your own voice, then record yourself. Bring the English on the page into your practice.' },
    ],
    newsSampleTitle: 'Small ideas for a more walkable city.',
    newsSampleSentence: 'An AI agent can score well on familiar tests and still struggle with a new task.',
    newsSampleNote: 'Illustrative article and sentence showing the practice flow.',
    devicesTitle: 'From phone to computer.\nYour voice. Your practice, continued.',
    devicesIntro: 'Log in to the same account to access your saved voice, practice history, and recordings on another device. Pick up where you left off, on the screen that suits you.',
    deviceLabels: ['Computer', 'Phone', 'Tablet'],
    researchTitle: 'Learning with your own voice.\nThe research behind the idea.',
  },
  ko: {
    heroTitle: '원어민처럼 말하는 나를,\n내 목소리로 먼저 들어보세요.',
    heroIntro: '내 목소리를 바탕으로, 목표로 하는 발음과 리듬의 예시를 만듭니다. 듣고, 말하고, 비교하세요. 연습 결과는 다음 맞춤 레슨으로 이어집니다.',
    voiceTitle: '목소리는 나답게.\n발음은 목표하는 소리로.',
    voiceIntro: '녹음한 목소리로 나와 비슷한 음색의 영어 발음 예시를 만듭니다. 내 녹음과 비교하며, 익히고 싶은 발음과 리듬을 연습해 보세요.',
    inputLabel: '지금 내가 녹음한 목소리',
    outputLabel: '내 목소리로 만든 AI 발음 예시',
    voiceCaption: '녹음에서 발음 예시를 만드는 과정을 보여주는 이미지입니다. 학습 전후의 성과를 나타내지 않습니다.',
    lessonTitle: '연습 결과에 따라,\n다음에 연습할 문장이 달라집니다.',
    lessonIntro: '발음, 강세, 리듬, 억양, 유창성의 다섯 가지 항목을 확인하세요. 다듬어야 할 소리와 연습 기록을 다음 레슨에 반영합니다.',
    lessonSteps: [
      { title: '연습할 소리를 찾으세요.', body: '예를 들어 thought와 worth의 /θ/. 어떤 단어의 어떤 소리를 연습할지 확인할 수 있습니다.' },
      { title: '어떻게 바꿀지 알아보세요.', body: '혀끝을 위아래 치아 사이에 가볍게 대고, 목소리를 내지 않은 채 바람을 내보내세요. 구체적인 조언을 직접 시도해 보세요.' },
      { title: '다음 문장에서도 같은 소리를.', body: '결과에 맞춰 다음 레슨을 구성합니다. 발음 예시를 듣고, 새로운 문장에서도 같은 소리를 연습하세요.' },
    ],
    lessonSampleLabel: '실제 평가 화면 · 데모 데이터',
    lessonNextLabel: '다음 레슨',
    newsTitle: '내 관심사가 영어 교재로.',
    newsIntro: '관심 있는 기사를 내 목소리로 듣고, 한 문장씩 발음을 연습하세요. 궁금한 이야기가 영어를 만나는 계기가 됩니다.',
    newsStages: [
      { title: '좋아하는 주제부터.', body: '테크놀로지, 문화, 여행, 과학. 더 알고 싶은 주제를 고르세요.' },
      { title: '궁금한 기사를 읽으세요.', body: '세상 이야기를 영어로 읽어보세요. 눈길이 가는 한 문장이 오늘의 연습이 됩니다.' },
      { title: '내 목소리로 연습하세요.', body: '내 목소리로 된 발음 예시를 듣고 녹음해 보세요. 기사 속 영어를 직접 소리 내어 말해 보세요.' },
    ],
    newsSampleTitle: '걷기 좋은 도시를 만드는 작은 아이디어.',
    newsSampleSentence: 'An AI agent can score well on familiar tests and still struggle with a new task.',
    newsSampleNote: '기사와 문장은 연습 과정을 소개하기 위한 예시입니다.',
    devicesTitle: '스마트폰에서도, PC에서도.\n내 목소리와 함께, 연습을 이어가세요.',
    devicesIntro: '같은 계정으로 로그인하면 저장한 내 목소리, 연습 기록, 녹음을 다른 기기에서도 확인할 수 있습니다. 편한 화면에서 연습을 이어가세요.',
    deviceLabels: ['컴퓨터', '스마트폰', '태블릿'],
    researchTitle: '내 목소리로 배우는 영어.\n연구에서 찾은 가능성.',
  },
}
