import React from 'react';
import {ArrowUpRight,CaretDown} from '@phosphor-icons/react';
import {LAUNCH_OFFER as offer,annualComparison as comparison} from './launch-offer.mjs';
import './pricing.css';
const copy={
 ja:{title:'自分の声で、続けていこう。',intro:'本人声のお手本・発音評価・個別練習・ニュースを、月払いでも年払いでも。',prelaunch:'有料プランは販売準備中です。以下は発売時の予定価格です。',tax:'すべて税込。',names:['月払い','年払い','買い切り'],descriptions:['まずは、ひと月ずつ。','一年かけて、習慣に。','買い切りをご希望の方へ。'],normal:'通常月額',normalYear:'通常月払い12回分',launch:'リリース記念',units:['最初の有料1か月','/ 年','一度のお支払い'],monthlyRenew:'2回目以降は {amount}／月で自動更新。',monthlyTotal:'有料12か月の合計は {amount}。',annualEquivalent:'月換算 {amount}。年額一括払い。',annualRenew:'翌年も {amount}で自動更新。',saving:'年間{amount}・約{percent}%お得',basis:'通常月額{amount}×12回との比較（初月割引なし）。',lifetimeStatus:'検討中・販売予定は未定',lifetimeNote:'表示額は想定価格です。提供範囲・条件を検討しており、現在は購入できません。',trial:'月払い・年払いは初回7日間無料の予定',trialNote:'声の準備後に、支払い方法を登録してお申し込み。無料期間後、月払いは初回980円・以後月1,480円、年払いは11,760円を一括請求します。初回請求前の解約で料金はかかりません。',cancel:'初月割引は新規の月払い契約で1人1回。年払いとは併用できません。次回更新前に解約でき、支払済み期間の終了まで利用できます。',features:['自分の声をもとにしたお手本','録音への発音フィードバック','結果に合わせた次の練習','ニュースのAI読み上げ'],cta:'Webで先行体験する',stage:'現在は先行体験のみ。ここから有料契約は開始しません。'},
 en:{title:'Keep going, in your own voice.',intro:'Own-voice models, pronunciation feedback, personalized practice and news — with either subscription.',prelaunch:'Paid plans are not on sale yet. These are planned launch prices.',tax:'Tax included. All charges in Japanese yen.',names:['Monthly','Annual','One-time purchase'],descriptions:['Start one month at a time.','Make it a year-long habit.','Prefer a one-time purchase?'],normal:'Regular monthly price',normalYear:'12 regular monthly payments',launch:'Launch offer',units:['first paid month','/ year','paid once'],monthlyRenew:'Then renews at {amount}/month.',monthlyTotal:'Total for 12 paid months: {amount}.',annualEquivalent:'Equivalent to {amount}/month. Billed annually upfront.',annualRenew:'Renews at {amount} each year.',saving:'Save {amount}/year · about {percent}%',basis:'Compared with {amount} × 12 regular payments, without the first-month offer.',lifetimeStatus:'Under consideration · not on sale',lifetimeNote:'This is an estimated price. Scope and terms are still being considered; this option cannot be purchased.',trial:'A 7-day first trial is planned for both subscriptions',trialNote:'Subscribe with a payment method after your voice is ready. After the trial: monthly ¥980 for the first paid month, then ¥1,480/month; annual ¥11,760 upfront. Cancel before the first charge to pay nothing.',cancel:'The monthly introductory offer is for new subscribers, once per person; it does not apply to annual billing. Cancel before renewal. Access continues until the end of the paid period.',features:['A model based on your own voice','Pronunciation feedback on recordings','Next practice informed by results','AI narration of news'],cta:'Try the web pilot',stage:'The pilot is available now. This link does not start a paid subscription.'},
 ko:{title:'내 목소리로, 계속해요.',intro:'내 목소리 예시·발음 피드백·맞춤 연습·뉴스를 월간과 연간 모두에서.',prelaunch:'유료 요금제는 판매 준비 중입니다. 아래는 출시 예정 가격입니다.',tax:'세금 포함. 일본 엔으로 결제됩니다.',names:['월간','연간','일회성 구매'],descriptions:['한 달씩 시작해요.','일 년 동안 습관으로 만들어요.','일회성 구매를 원하시나요?'],normal:'정상 월 요금',normalYear:'정상 월 요금 12회 합계',launch:'출시 기념',units:['첫 유료 1개월','/ 년','한 번 결제'],monthlyRenew:'두 번째 결제부터 월 {amount}로 자동 갱신됩니다.',monthlyTotal:'유료 12개월 합계 {amount}.',annualEquivalent:'월 환산 {amount}. 연간 요금 일괄 결제.',annualRenew:'다음 해에도 {amount}로 자동 갱신됩니다.',saving:'연간 {amount} · 약 {percent}% 절약',basis:'정상 월 요금 {amount}×12회 대비. 첫 달 할인은 제외.',lifetimeStatus:'검토 중 · 판매 일정 미정',lifetimeNote:'예상 가격입니다. 제공 범위와 조건을 검토 중이며 현재 구매할 수 없습니다.',trial:'월간·연간 첫 7일 무료 체험 예정',trialNote:'목소리 준비 후 결제 수단을 등록해 신청합니다. 무료 기간 후 월간은 첫 유료 월 ¥980, 이후 월 ¥1,480, 연간은 ¥11,760 일괄 청구입니다. 첫 결제 전 해지하면 요금이 없습니다.',cancel:'첫 달 할인은 신규 월간 구독자 1인 1회이며 연간에는 적용되지 않습니다. 다음 갱신 전 해지할 수 있고 결제 기간이 끝날 때까지 이용 가능합니다.',features:['내 목소리를 바탕으로 한 모델 음성','녹음에 대한 발음 피드백','결과에 맞춘 다음 연습','AI 뉴스 읽기'],cta:'웹에서 먼저 체험하기',stage:'현재는 선행 체험만 가능합니다. 이 링크로 유료 구독이 시작되지 않습니다.'}
};
export default function Pricing({lang='ja'}){
 const c=copy[lang]||copy.en;
 const money=amount=>`¥${new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(amount)}`;
 const fill=(text,amount)=>text.replace('{amount}',money(amount)).replace('{percent}',comparison.percent);
 const brief={ja:{title:'まずは7日間、自分の声で。',ready:'有料プランは準備中。発売時の予定価格・税込。',trial:'無料体験',days:'7日間',free:'無料',try:'自分の声で、聴く・話す・振り返る。',card:'支払い方法の登録が必要',stop:'初回請求前の解約で料金なし',details:'無料体験・更新の条件',renew:'以後 {amount}／月',yearRenew:'年額一括・翌年も {amount}',basis:'通常月額×12回との比較',extra:'買い切りは検討中です。',launch:'リリース記念・初回のみ'},en:{title:'Seven days. Your own voice.',ready:'Paid plans are coming soon. Planned prices in JPY, tax included.',trial:'Free trial',days:'7 days',free:'Free',try:'Listen, speak and reflect in your own voice.',card:'Payment method required',stop:'No charge if canceled before billing',details:'Trial and renewal terms',renew:'Then {amount}/month',yearRenew:'Billed annually. Renews at {amount}',basis:'Compared with 12 regular monthly payments',extra:'A one-time option is under consideration.',launch:'Launch offer · first paid month'},ko:{title:'먼저 7일, 내 목소리로.',ready:'유료 요금제 준비 중. 출시 예정 가격·세금 포함·일본 엔.',trial:'무료 체험',days:'7일',free:'무료',try:'내 목소리로 듣고, 말하고, 돌아봐요.',card:'결제 수단 등록 필요',stop:'첫 결제 전 해지하면 요금 없음',details:'체험·갱신 조건',renew:'이후 월 {amount}',yearRenew:'연간 일괄 결제 · 갱신 {amount}',basis:'정상 월 요금 12회 대비',extra:'일회성 구매는 검토 중입니다.',launch:'출시 기념 · 첫 유료 월'}}[lang]||null;
 const b=brief||{title:c.title,ready:c.prelaunch};
 const labels={ja:{launch:'リリース記念',saving:'約33.8%お得',dailyMonth:'通常 約49円／日',dailyYear:'約32円／日',candidate:'候補プラン',estimate:'想定価格・未販売',basis:'税込。日額は通常月額÷30日、年額÷365日。年額割引は通常月額×12回との比較。'},en:{launch:'Launch offer',saving:'Save about33.8%',dailyMonth:'Normally ≈ ¥49/day',dailyYear:'≈ ¥32/day',candidate:'Under consideration',estimate:'Estimated · not on sale',basis:'Tax included, JPY. Daily equivalents: regular monthly price ÷30; annual price ÷365. Annual savings compare 12 regular monthly payments.'},ko:{launch:'출시 기념',saving:'약33.8% 절약',dailyMonth:'정상가 약 ¥49/일',dailyYear:'약 ¥32/일',candidate:'후보 요금제',estimate:'예상 가격·판매 전',basis:'세금 포함·일본 엔. 일 환산: 정상 월 요금÷30일, 연 요금÷365일. 연간 할인은 정상 월 요금12회 대비.'}}[lang]||null;
 const l=labels||{};
 return <section id="pricing" className="launch-pricing section wrap" aria-labelledby="pricing-title">
  <div className="launch-pricing-heading"><h2 id="pricing-title">{b.title}</h2></div>
  <div className="launch-pricing-options">
   <article className="launch-plan launch-plan-trial"><h3>{b.trial}</h3><p className="launch-plan-price"><strong>{b.days}</strong><span>{b.free}</span></p><p className="launch-plan-equivalent">{b.card}<br/>{b.stop}</p><a className="action" href="https://voice.maepace.com/">{c.cta}<ArrowUpRight size={18} aria-hidden="true"/></a></article>
   <article className="launch-plan launch-plan-monthly"><h3>{c.names[0]}</h3><div className="launch-offer-line"><s>{money(offer.monthly)}</s><span className="launch-balloon">{l.launch}</span></div><p className="launch-plan-price"><strong>{money(offer.firstMonth)}</strong><span>{c.units[0]}</span></p><p className="launch-daily">{l.dailyMonth}</p><p className="launch-plan-renewal">{fill(b.renew,offer.monthly)}</p></article>
   <article className="launch-plan launch-plan-annual"><h3>{c.names[1]}</h3><div className="launch-offer-line"><s>{money(comparison.regularTotal)}</s><span className="launch-balloon">{l.saving}</span></div><p className="launch-plan-price"><strong>{money(offer.annual)}</strong><span>{c.units[1]}</span></p><p className="launch-daily">{l.dailyYear}</p><p className="launch-plan-renewal">{fill(b.yearRenew,offer.annual)}</p></article>
   <article className="launch-plan launch-plan-lifetime"><h3>{c.names[2]}</h3><div className="launch-offer-line">{l.candidate}</div><p className="launch-plan-price"><strong>{money(offer.lifetimeEstimate)}</strong></p><p className="launch-daily">{l.estimate}</p></article>
  </div>
  <details className="launch-pricing-disclosure"><summary>{b.details}<CaretDown size={18} aria-hidden="true"/></summary><p>{l.basis}</p><p>{c.prelaunch}</p><p>{c.trialNote}</p><p>{c.cancel}</p><p>{c.lifetimeNote}</p></details>
 </section>;
}
