import React,{useEffect,useRef,useState} from 'react';
import {Headphones,ArrowRight} from '@phosphor-icons/react';
import speaker from './assets/undraw/speaker.svg?url';
import worried from './assets/undraw/worried-person.svg?url';
import intelligence from './assets/undraw/ai-intelligence.svg?url';
import practice from './assets/undraw/practice-speaker.svg?url';
function useStoryMotion(count,delay=1200){const ref=useRef(null);const [reduce,setReduce]=useState(false);useEffect(()=>{const query=window.matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setReduce(query.matches);query.addEventListener('change',update);update();return()=>query.removeEventListener('change',update)},[]);const [paused,setPaused]=useState(false),[visible,setVisible]=useState(false),[step,setStep]=useState(0);useEffect(()=>{const el=ref.current;if(!el)return;let intersecting=false;const sync=()=>setVisible(intersecting&&!document.hidden);const observer=new IntersectionObserver(([e])=>{intersecting=e.isIntersecting;sync()},{threshold:.2});observer.observe(el);document.addEventListener('visibilitychange',sync);return()=>{observer.disconnect();document.removeEventListener('visibilitychange',sync)}},[]);const running=visible&&!paused&&!reduce;useEffect(()=>{if(!running)return;const timer=setInterval(()=>setStep(s=>(s+1)%count),delay);return()=>clearInterval(timer)},[running,count,delay]);return{ref,step:Math.min(step,count-1),running,reduce,paused,toggle:()=>setPaused(p=>!p)}}
export function VoiceMotion({lang}){
 const state=useStoryMotion(3);
 const c={ja:{labels:['声を録音する','自分の声のお手本に','聴いて、発音する'],notes:['まずは、あなたの声を登録。','声質はあなた。発音はネイティブ。','目指す声を聴いて、まねしてみる。'],note:'利用イメージ。初回に音声登録と同意が必要です。'},en:{labels:['Record your voice','Meet your voice model','Listen. Speak. Repeat.'],notes:['Start with your own recording.','Your voice. Native pronunciation.','Hear your model, then try it yourself.'],note:'Illustration. Voice registration and consent required.'},ko:{labels:['내 목소리 녹음','내 목소리의 발음 예시','듣고, 따라 말하기'],notes:['먼저 내 목소리를 등록해요.','목소리는 나답게, 발음은 원어민처럼.','목표 발음을 듣고 따라 해요.'],note:'이용 예시. 목소리 등록과 동의가 필요합니다.'}}[lang];
 return <div className="voice-motion voice-triptych" ref={state.ref} data-step={state.step} data-running={state.running}><ol className="voice-illustrated-steps">{[speaker,intelligence,practice].map((art,i)=><li key={art} className={state.step===i?'current':''}><div className="voice-step-art"><img src={art} width="300" height="260" alt=""/>{i<2&&<ArrowRight className="voice-step-arrow" size={30} aria-hidden="true"/>}</div><h2><span>{String(i+1).padStart(2,'0')}</span>{c.labels[i]}</h2></li>)}</ol></div>;
}
export function SearchMotion({lang}){const state=useStoryMotion(4,1000);const c={ja:{title:'シャドーイング、何度も続けてきた。',label:'お手本を探し続けるイメージ',genres:['会話','ニュース','映画','スピーチ','旅','ポッドキャスト']},en:{title:'So many voices. So much practice.',label:'Illustration of searching for a model',genres:['Talks','News','Films','Speeches','Travel','Podcasts']},ko:{title:'많이 듣고, 여러 번 따라 했어요.',label:'발음 예시를 계속 찾는 모습',genres:['대화','뉴스','영화','연설','여행','팟캐스트']}}[lang];return <div className="search-motion" ref={state.ref} data-running={state.running}><p>{c.title}</p><div className="search-motion-field" aria-label={c.label}><div className="falling-materials" aria-hidden="true">{[...c.genres,...c.genres].map((label,i)=><div className="falling-material" key={i} style={{'--lane':`${[3,65,18,72,0,56,29,77,7,62,22,70][i]}%`,'--tilt':`${i%2?12:-15}deg`,'--delay':`${-i*.31}s`}}><Headphones size={20}/><span>{label}</span><i/><i/></div>)}</div><img src={worried} width="160" height="230" alt=""/></div></div>}
