import React from 'react';
import {Microphone,Headphones,ArrowDown,SpeakerHigh} from '@phosphor-icons/react';
import speaker from './assets/undraw/speaker.svg?url';
const copy={
 ja:{title:'探していたお手本は、\nあなたの声。',intro:'似た声の人を、もう探さなくていい。\n声の個性はそのままに、目指す発音を聴く。',steps:['あなたの声を登録','AIが、発音のお手本に','お手本と、聴き比べる'],bodies:['まずは自分の声を録音。','声質をもとに、英語の発音モデルを作成。','同じ文を話して、音の違いを確かめる。'],voice:'あなたの声質',pronunciation:'目指す発音',model:'AIのお手本',recording:'自分の録音',note:'仕組みのイメージ。初回に音声登録と同意が必要です。',next:'そして、苦手な音から次の練習へ。'},
 en:{title:'The model you were\nlooking for is you.',intro:'Stop searching for someone with a similar voice.\nHear the pronunciation you aim for in a voice like yours.',steps:['Register your voice','AI creates your model','Listen. Compare. Practice.'],bodies:['Start by recording your own voice.','Your vocal identity shapes the pronunciation model.','Say the same sentence and listen for differences.'],voice:'Your vocal identity',pronunciation:'Target pronunciation',model:'AI model',recording:'Your recording',note:'Illustration of the process. Voice registration and consent are required.',next:'Then, practice the sounds that need attention.'},
 ko:{title:'찾던 발음 예시,\n바로 내 목소리.',intro:'나와 비슷한 목소리를 더는 찾지 않아도 돼요.\n목소리의 개성은 그대로, 원하는 발음을 들어보세요.',steps:['내 목소리 등록','AI가 발음 예시로','듣고 비교하며 연습'],bodies:['먼저 내 목소리를 녹음해요.','내 음색을 바탕으로 영어 발음 예시를 만들어요.','같은 문장을 말하고 소리의 차이를 확인해요.'],voice:'내 음색',pronunciation:'목표 발음',model:'AI 발음 예시',recording:'내 녹음',note:'이용 과정 예시. 처음에는 목소리 등록과 동의가 필요합니다.',next:'이제, 어려운 소리부터 다음 연습으로.'}
};
export default function VoiceMechanism({lang}){
 const c=copy[lang];
 return <section id="voice" className="voice-mechanism section wrap"><div className="mechanism-intro"><h2>{c.title}</h2><p>{c.intro}</p><img src={speaker} alt="" width="370" height="365" loading="lazy"/></div><ol className="mechanism-steps"><li><span className="mechanism-number">01</span><div><h3>{c.steps[0]}</h3><div className="mechanism-record" aria-hidden="true"><Microphone size={28}/><span>Could you say that again?</span></div></div></li><li><span className="mechanism-number">02</span><div><h3>{c.steps[1]}</h3><div className="mechanism-equation"><span>{c.voice}</span><b aria-hidden="true">×</b><span>{c.pronunciation}</span></div></div></li><li><span className="mechanism-number">03</span><div><h3>{c.steps[2]}</h3><div className="mechanism-compare"><span><Headphones size={23}/>{c.model}</span><span><SpeakerHigh size={23}/>{c.recording}</span></div></div></li></ol><p className="mechanism-note">{c.note}</p><p className="mechanism-next">{lang==='ja'?<span>そして、苦手な音から<span className="phrase">次の練習へ。</span></span>:c.next}<ArrowDown size={26}/></p></section>;
}
